### ISSUE TITLE
[v4] Pseudo selector scale doesn't work on Firefox

### ISSUE THREAD

**Issue by coolemur** [tailwindlabs/tailwindcss#13577]
**What version of Tailwind CSS are you using?**

v4.0.0-alpha.14

**What browser are you using?**

For example: Firefox

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/9oZbag3cwc

**Describe your issue**

Pseudo element scale doesn't work in Firefox browser, while it works in other browsers 

To reproduce, check hover effect and compare it in Chrome vs Firefox

**Comment by RobinMalfait** [comment]
Hey!

This is an expected issue and by design. We use the new `@property` CSS feature which isn't available in Firefox yet. It will be once we release v4.

Right now, you can either use another browser or use Firefox Nightly (which does have `@property` support).

**Comment by HiggsWRX** [comment]
> Hey!
> 
> This is an expected issue and by design. We use the new `@property` CSS feature which isn't available in Firefox yet. It will be once we release v4.
> 
> Right now, you can either use another browser or use Firefox Nightly (which does have `@property` support).

Hey @RobinMalfait , would you mind clearing up something for me?

You say that firefox (not nightly) will have @property support when Tailwind v4 releases. But this means a lot of the features of TWv4 will not work for a lot of people since not everyone updates their browser that regularly.

Will this be polyfilled?

Will the firefox themselves polyfill it to achieve backwards compatibility?

How will that work? It confuses me a bit because there's dozens of issues opened here because of the same thing, the team provides no fallbacks because "it will be available when TWv4 releases" and only says that a fallback/polyfill is "under consideration". How can that be?

**Comment by coolemur** [comment]
Yeah.... "just use other browser" suggestion was very interesting indeed. And then issue closed instantly like this is solved...

Imagine service: "You car aint working? Just buy new one".

**Comment by Andrewij21** [comment]
Any progress about this issue?

**Comment by RobinMalfait** [comment]
@HiggsWRX Firefox already shipped the `@property` and the Firefox browser is evergreen so the moment somebody restarts their computer or browser they will be on the latest version. 

That said, we also shipped a polyfill that makes it work with older browsers.

---

@coolemur I'm not saying to _always_ use another browser, I'm saying to use another browser "right now", while Tailwind CSS v4 is still in alpha. In the meantime we shipped a polyfill so this is not an issue anymore.

---

@Andrewij21 nothing to report, it should just work. If not, please open a new issue with a minimal reproduction repo attached if you are running into any issues.

**Comment by Andrewij21** [comment]
@RobinMalfait thanks for your answer but apparently it still not work, 
```
 <Link
            href={link.href}
            className="relative text-primary hover:text-primary-foreground group"
          >
            <span className="block rounded absolute inset-0 group-hover:bg-primary scale-0 group-hover:scale-100 duration-300 ease-out origin-center"></span>
            <p className="relative z-10 block px-2 py-1">{link.label}</p>
          </Link>
          
```
i tried to run this next.Js code in chrome and its working, i don't know why but in firefox its just wont work

i'am using the latest firefox 130.0.1

**Comment by RobinMalfait** [comment]
@Andrewij21 can you create share a minimal reproduction via https://play.tailwindcss.com (make sure to set the version to v4 alpha in the dropdown before sharing).

I tried with your example, and while the location is a bit off the actual scaling works for me in Safari and Firefox. Does this work for you? 

https://play.tailwindcss.com/SdZ6pFOX27

**Comment by Andrewij21** [comment]
@RobinMalfait thanks for your answer, my bad i'm using tailwind ^3.4.1.

i tried to update it to `version [4.0.0-alpha.21]`, but i got confused 😅 and because im using shadcn too.

i think just stick with ^3.4.1 for now.
