### ISSUE TITLE
`backdrop-blur-` does not work on webkit browsers (ie safari)

### ISSUE THREAD

**Issue by t3duk** [tailwindlabs/tailwindcss#13844]
**What version of Tailwind CSS are you using?**
`v3.4.4`

**What build tool (or framework if it abstracts the build tool) are you using?**

Next `v14.2.2`
PostCSS `v8`

**What version of Node.js are you using?**

Node `v20.11.1`
Bun `v1.1.8`

**What browser are you using?**

Safari [macOS/iOS] (does **NOT** work as expected) `v17.5`
Brave [Windows] (works as expected) `v1.67.116`
Arc [macOS] (works as expected) `v1.47.1`
Edge [Windows] (works as expected) `v126.0.2592.56`

**What operating system are you using?**

macOS 14.5
Windows 11 23H2

**Reproduction URL**

https://play.tailwindcss.com/s0uKhW1RIh

<img src="https://my.fags.men/ted/24-06/Untitlfd.png">
<img src="https://my.fags.men/ted/24-06/Untitled.png">

**Describe your issue**

The `backdrop-blur-` classes do not add the `-webkit-` style, so Safari and other webkit browsers aren't being styled with a backdrop blur.

In this mean while, ot solve this I manually added each of the classes to my global css file
```css
.backdrop-blur-3xl {
  --tw-backdrop-blur: blur(64px);
  -webkit-backdrop-filter: var(--tw-backdrop-blur);
  backdrop-filter: var(--tw-backdrop-blur);
}
...etc
```

**Comment by thecrypticace** [comment]
Hey! In your own projects this is handled by `autoprefixer` which uses your `browserslist` configuration to determine supported browsers and what prefixes need to be applied. As for Tailwind Play, there was a configuration issue (also related to autoprefixer) that caused this but I've fixed it and your Play now works shows the blur correctly!

Thanks for letting us know 👍

**Comment by Muhammed-Rahif** [comment]
> As for Tailwind Play, there was a configuration issue (also related to autoprefixer) that caused this but I've fixed it and your Play now works and shows the blur correctly!
@thecrypticace what was that configuration issue?

I can still see this issue on webkit even after using `autoprefixer` and `browserslist`. Also there is some strange thing, when I manually put the css variable value from inspector(copy) to inspector(paste), then it works:

https://github.com/user-attachments/assets/3cb54c14-843a-49d8-9a00-85d9961a502b

**Comment by thecrypticace** [comment]
@Muhammed-Rahif What browser is that? It's working here.

**Comment by Muhammed-Rahif** [comment]
It's a tauri instance: https://tauri.app/start/

**Comment by Muhammed-Rahif** [comment]
FYI: Tauri uses WRY (WebKitGTK for Linux, WebKit for MacOS, Webview2 for Windows). And I am using tauri on linux.
_Source: https://github.com/Elanis/web-to-desktop-framework-comparison#major-characteristics_

**Comment by thecrypticace** [comment]
I wonder if it's a much older webkit version where variable fallbacks worked a bit differently. 🤔

**Comment by thecrypticace** [comment]
I'll see if I can spin up a linux box and give it a test (may not happen today but hopefully this week)

**Comment by Heraclito-Q-Saldanha** [comment]
any update?

**Comment by Heraclito-Q-Saldanha** [comment]
Why is this issue closed? I can reproduce

**Comment by rayanmestiri** [comment]
I have the exact same issue on Orion Browser version 0.99.130.2 on macOS which uses WebKit 621.1.2.111.4.
I can reproduce the steps in the video by putting the value manually in the web inspector.

**Comment by ADTC** [comment]
### Using Safari Desktop Version 18.2 (19620.1.16.111.6, 19620):

Very odd: `var` does not work with `-webkit-backdrop-filter`. Even though Safari tells me that the variable has a value, it doesn't apply any blur effect on the element:

<img width="361" alt="Image" src="https://github.com/user-attachments/assets/1290450c-ced3-48d4-b9b3-cb37a9473824" />

Using `var` inside `blur` also **_does not_** work:

<img width="352" alt="Image" src="https://github.com/user-attachments/assets/ace2ac14-0518-4d7b-a1b9-ff3815767149" />

I can test and find that the variable works for `border-width` but not for `-webkit-backdrop-filter`:

<img width="358" alt="Image" src="https://github.com/user-attachments/assets/e01f031e-730c-44d1-8f48-15433f44aa71" />

### **This is the only way to get the blur working in Safari:**

If I directly apply the actual value, then the blur effect works and is applied on the element.

<img width="359" alt="Image" src="https://github.com/user-attachments/assets/ea7d2966-0950-4c4e-9210-dc2d18cd2b81" />

This would mean the Tailwind generated CSS here does not work in Safari:

```css
.backdrop-blur-sm {
  --tw-backdrop-blur: blur(var(--blur-sm));
  -webkit-backdrop-filter: var(--tw-backdrop-blur,) var(--tw-backdrop-brightness,) var(--tw-backdrop-contrast,) var(--tw-backdrop-grayscale,) var(--tw-backdrop-hue-rotate,) var(--tw-backdrop-invert,) var(--tw-backdrop-opacity,) var(--tw-backdrop-saturate,) var(--tw-backdrop-sepia,);
  backdrop-filter: var(--tw-backdrop-blur,) var(--tw-backdrop-brightness,) var(--tw-backdrop-contrast,) var(--tw-backdrop-grayscale,) var(--tw-backdrop-hue-rotate,) var(--tw-backdrop-invert,) var(--tw-backdrop-opacity,) var(--tw-backdrop-saturate,) var(--tw-backdrop-sepia,);
}
```

We have to override it and insert all the **actual** values for Safari:

```css
  -webkit-backdrop-filter: blur(8px) brightness( ... etc. ) etc.;
```

Please re-open or tell us if we should open a new issue.

**Comment by thecrypticace** [comment]
Looks like it works to me (with and without the `@property`): https://play.tailwindcss.com/xuWb6hIqXV?file=css

<img width="1174" alt="Image" src="https://github.com/user-attachments/assets/0c455cbd-cf17-4757-ac9b-b15d483a2b32" />

**Comment by thecrypticace** [comment]
Safari 18.3 — this worked in 18.2 and before as well. This is why I also gave a link to to the Play.

**Comment by ADTC** [comment]
I updated to Safari Desktop Version 18.3 (19620.2.4.111.8, 19620) but still:

Variable does not work:

<img width="751" alt="Image" src="https://github.com/user-attachments/assets/87863a2f-bacb-412b-835d-534b43e7393c" />

This version also does not work, even if it does the fallback:

```css
--my-var2: 20px; /* disable to do the fallback */
-webkit-backdrop-filter: blur(var(--my-var2, 5px));
```

Only inline fixed value works:

<img width="761" alt="Image" src="https://github.com/user-attachments/assets/49b8dbd1-fed0-4a1b-843f-890d84dd4958" />

### Conclusion
It looks like Safari doesn't support CSS variables in `-webkit-backdrop-filter` for some odd reason.

**Comment by thecrypticace** [comment]
What OS are you running? and hardware?

It absolutely does support CSS variables so the fact that it's not working for you is almost certainly a bug in WebKit.

**Comment by ADTC** [comment]
@thecrypticace Apple M1 Pro, macOS Sonoma 14.7.2 (23H311), MacBook Pro.

There's no VM.

**Comment by ADTC** [comment]
This looks like an eerily similar problem but for a different property: http://aaronpinero.net/learned/posts/2024/04/2024-04-17/

**Comment by ADTC** [comment]
Any thoughts on this?

**Comment by ADTC** [comment]
[BTW I have acquired more information about this.](https://github.com/mdn/browser-compat-data/issues/25914#issuecomment-2676190245)

**Comment by hansf14** [comment]
After a few testing, for me, the issue was caused by the **trailing commas** after the **`var`**.
`var(--tw-backdrop-blur,)` => should be `var(--tw-backdrop-blur)` and so on.
This issue could be seen in **only some** versions of **Safari** as I tested.
I made a plugin to fix this problem.
`> npm install -D @hansf14/postcss-hotfix` or > `yarn add -D @hansf14/postcss-hotfix`
Hope this helps.

**Comment by CyberVy** [comment]
> ### Using Safari Desktop Version 18.2 (19620.1.16.111.6, 19620):
> 
> Very odd: `var` does not work with `-webkit-backdrop-filter`. Even though Safari tells me that the variable has a value, it doesn't apply any blur effect on the element:
> 
> <img alt="Image" width="361" src="https://private-user-images.githubusercontent.com/6047296/412806843-1290450c-ced3-48d4-b9b3-cb37a9473824.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODY0NjIwMTUsIm5iZiI6MTc4NjQ2MTcxNSwicGF0aCI6Ii82MDQ3Mjk2LzQxMjgwNjg0My0xMjkwNDUwYy1jZWQzLTQ4ZDQtYjliMy1jYjM3YTk0NzM4MjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA4MTFUMTUyMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY5NjU4ZjlkMjQ5Yjg4OWI2OTY4NDM3ZmE5OGJkMDY4ZmZmOTBiZTZkZmNkOGJhZmM4NGFjNTIyMWI4ZTY5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.zGZMj-MnAGCLytYSqozgeW0CNjAt9k3XFFomge7qdMk">
> Using `var` inside `blur` also **_does not_** work:
> 
> <img alt="Image" width="352" src="https://private-user-images.githubusercontent.com/6047296/412808849-ace2ac14-0518-4d7b-a1b9-ff3815767149.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODY0NjIwMTUsIm5iZiI6MTc4NjQ2MTcxNSwicGF0aCI6Ii82MDQ3Mjk2LzQxMjgwODg0OS1hY2UyYWMxNC0wNTE4LTRkN2ItYTFiOS1mZjM4MTU3NjcxNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA4MTFUMTUyMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQwMjAwYjQ3MTViMTYzMGVjNDkwYjRhZWI3ZGExMjgwOTMzMzRiYTk0OTNkMjg1MDhhNzZkZDlhNGI3ZGQ2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.uCBOUvJBq36fcSA0aps3ldNkkBVeFp5tgfxELnXbErI">
> I can test and find that the variable works for `border-width` but not for `-webkit-backdrop-filter`:
> 
> <img alt="Image" width="358" src="https://private-user-images.githubusercontent.com/6047296/412812091-e01f031e-730c-44d1-8f48-15433f44aa71.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODY0NjIwMTUsIm5iZiI6MTc4NjQ2MTcxNSwicGF0aCI6Ii82MDQ3Mjk2LzQxMjgxMjA5MS1lMDFmMDMxZS03MzBjLTQ0ZDEtOGY0OC0xNTQzM2Y0NGFhNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA4MTFUMTUyMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmYzODg1MGE1MjE1MDU3YWQ1YWFiOGNhZWUxOWZlNDM5NGE5MmQ5YjY0NDY0ODI4NmRlNzQzY2EyMzNiNjIyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.izcLliFRaqmbW1SBdcEL4MkyOYOi7i1AuxB6zJIbALg">
> ### **This is the only way to get the blur working in Safari:**
> 
> If I directly apply the actual value, then the blur effect works and is applied on the element.
> 
> <img alt="Image" width="359" src="https://private-user-images.githubusercontent.com/6047296/412807298-ea7d2966-0950-4c4e-9210-dc2d18cd2b81.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODY0NjIwMTUsIm5iZiI6MTc4NjQ2MTcxNSwicGF0aCI6Ii82MDQ3Mjk2LzQxMjgwNzI5OC1lYTdkMjk2Ni0wOTUwLTRjNGUtOTIxMC1kYzJkMThjZDJiODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA4MTFUMTUyMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTFkMWY2Yzc5YzNlOTNmZTJjZjVhODAwMDY0MTdkODViOWE2ZTVjZTZiYTExNTYzMGRkMzM3NDI5MmQ3YmI0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.9YygnH50AHvDIzMNXH9ErZl5StdUOskMLNz3ZU-Iykc">
> This would mean the Tailwind generated CSS here does not work in Safari:
> 
> .backdrop-blur-sm {
>   --tw-backdrop-blur: blur(var(--blur-sm));
>   -webkit-backdrop-filter: var(--tw-backdrop-blur,) var(--tw-backdrop-brightness,) var(--tw-backdrop-contrast,) var(--tw-backdrop-grayscale,) var(--tw-backdrop-hue-rotate,) var(--tw-backdrop-invert,) var(--tw-backdrop-opacity,) var(--tw-backdrop-saturate,) var(--tw-backdrop-sepia,);
>   backdrop-filter: var(--tw-backdrop-blur,) var(--tw-backdrop-brightness,) var(--tw-backdrop-contrast,) var(--tw-backdrop-grayscale,) var(--tw-backdrop-hue-rotate,) var(--tw-backdrop-invert,) var(--tw-backdrop-opacity,) var(--tw-backdrop-saturate,) var(--tw-backdrop-sepia,);
> }
> We have to override it and insert all the **actual** values for Safari:
> 
>   -webkit-backdrop-filter: blur(8px) brightness( ... etc. ) etc.;
> Please re-open or tell us if we should open a new issue.

I can reproduce this issue on Safari 18.6. However it works fine on the WKWebview. I think it's a bug of macOS, which is hard to fix in tailwind side.
