### ISSUE TITLE
[v4] It looks like you're trying to use `tailwindcss` directly as a PostCSS plugin.

### ISSUE THREAD

**Issue by DanielOberlechner** [tailwindlabs/tailwindcss#15735]
**What version of Tailwind CSS are you using?**

4.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

"@tailwindcss/postcss": "^4.0.0", Angular 19.1.3

**What version of Node.js are you using?**

22.11.0

**What browser are you using?**

Chrome newest version

**What operating system are you using?**

macOS M3 Pro

**Describe your issue**
Today I try to upgrade to Tailwind v4, but without success.

I didn't use postcss, I just have Tailwind in my package.json, my tailwind.config.js and the @import tailwind in my main scss file.

If I upgrade the package to 4.0.0, I have the following error:
Error: It looks like you're trying to use `tailwindcss` directly as a PostCSS plugin. 
The PostCSS plugin has moved to a separate package, 
so to continue using Tailwind CSS with PostCSS 
you'll need to install `@tailwindcss/postcss` and update your PostCSS configuration.

I try to install @tailwind/postcss and create a PostCSS config file like this
`export default {
    plugins: {
        "@tailwindcss/postcss": {}
  }
}`

Has anyone any idea how to fix this problem?
On stackoverflow there is a similar question on this topic but the person is using the tailwind directive to import it.
I've solved that but I still get the same error.

Stackoverflow:
https://stackoverflow.com/questions/79380519/how-to-upgrade-tailwindcss

**Comment by philipp-spiess** [comment]
Yep this error means that for some reason `tailwindcss` is used as the PostCSS plugin instead of the new `@tailwindcss/postcss` plugin. Seems like you figured it out though 👍

**Comment by agm1984** [comment]
I found this helpful: https://stackoverflow.com/questions/79241624/integrating-tailwind-v4-alpha-with-vite-postcss-config
and https://tailwindcss.com/docs/installation/using-vite#installing-with-vite

**Comment by kayden1940** [comment]
> I found this helpful: https://stackoverflow.com/questions/79241624/integrating-tailwind-v4-alpha-with-vite-postcss-config and https://tailwindcss.com/docs/installation/using-vite#installing-with-vite

Doesn't work on my case, please reopen this issue

**Comment by chenlcacentury** [comment]
@DanielOberlechner  @philipp-spiess I think here is no solution so far in this case. All mentioned is for vite not angular. Can you re-open this issue ? Have to give up the upgrade and wait for update

**Comment by Mearman** [comment]
looks like I'm getting the same issue in NextJS

**Comment by bryantomoregie** [comment]
I'm using Vite and I just had to delete tailwindcss from my postcss plugins. Everything works fine now.

**Comment by DanielOberlechner** [comment]
https://tailwindcss.com/docs/installation/framework-guides/angular

You should create for Angular a .postcssrc.json with the following content:
{
  "plugins": {
    "@tailwindcss/postcss": {}
  }
}


Then it worked for me...

@Mearman 
Have a look at this:
https://tailwindcss.com/docs/installation/framework-guides/nextjs

**Comment by vdegenne** [comment]
"Everything's working finally going to bed!"
*wake up the next day*
*pour some coffee*
*sit on desk*
*press enter*
**Big explosion**
"Aaah don't you like being a web dev?"

**Comment by zenobios** [comment]
> https://tailwindcss.com/docs/installation/framework-guides/angular
> 
> You should create for Angular a .postcssrc.json with the following content: { "plugins": { "@tailwindcss/postcss": {} } }
> 
> Then it worked for me...
> 
> [@Mearman](https://github.com/Mearman) Have a look at this: https://tailwindcss.com/docs/installation/framework-guides/nextjs

Thanks for the hint. After adding the `.postcssrc.json` with the proposed content I'm able to at least start my Svelte project via `npm run dev`. However, I then get the following message in browser:

`[plugin:vite:css] [postcss] Missing "./base" specifier in "tailwindcss" package`

**Comment by vdegenne** [comment]
@zenobios are you using `@import "tailwindcss"` in your CSS?

**Comment by zenobios** [comment]
I'm using 
```ts
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

**Comment by vdegenne** [comment]
That's the problem.

**Comment by zenobios** [comment]
Alright, and what's the solution 😅? Sorry, I started using Svelte/SvelteKit along with Tailwind just a couple of weeks ago so I'm not an expert here and might miss something obvious.

**Comment by vdegenne** [comment]
> Alright, and what's the solution 😅? Sorry, I started using Svelte/SvelteKit along with Tailwind just a couple of weeks ago so I'm not an expert here and might miss something obvious.

In tailwindcss 4 you just have to use `@import "tailwindcss"`

Also I hardly recommend to read: https://tailwindcss.com/blog/tailwindcss-v4  
It's not that long and you'll learn all the new core concepts of tw4.

**Comment by hackathononly** [comment]
on Astro with Tailwind 4.0 : 

1. uninstall @astrojs/tailwind , install @tailwindcss/vite, 
2. on astro.config.mjs, remove reference to @astrojs/tailwind and import @tailwindcss/vite instead,
3. same file , change tailwind() integrations to tailwindcss()

**Comment by Suryanshu1005** [comment]
Has anyone able to fix the issue in nextjs? npm run build works fine when building locally but vercel gives this weird error. 

```
./node_modules/nprogress/nprogress.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!./node_modules/nprogress/nprogress.css
Error: It looks like you're trying to use `tailwindcss` directly as a PostCSS plugin. The PostCSS plugin has moved to a separate package, so to continue using Tailwind CSS with PostCSS you'll need to install `@tailwindcss/postcss` and update your PostCSS configuration.
    at Te (/vercel/path0/node_modules/tailwindcss/dist/lib.js:33:1740)
    at LazyResult.runOnRoot (/vercel/path0/node_modules/next/node_modules/postcss/lib/lazy-result.js:329:16)
    at LazyResult.runAsync (/vercel/path0/node_modules/next/node_modules/postcss/lib/lazy-result.js:258:26)
    at LazyResult.async (/vercel/path0/node_modules/next/node_modules/postcss/lib/lazy-result.js:160:30)
    at LazyResult.then (/vercel/path0/node_modules/next/node_modules/postcss/lib/lazy-result.js:404:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)
Import trace for requested module:
./node_modules/nprogress/nprogress.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!./node_modules/nprogress/nprogress.css
./node_modules/nprogress/nprogress.css
./src/app/_components/Loadingbar.tsx
```

**Comment by DanielOberlechner** [comment]
@Suryanshu1005 
Did you do whats written in this documentation?

https://tailwindcss.com/docs/installation/framework-guides/nextjs

**Comment by gaieges** [comment]
Had this same problem as a result of upgrading to v4 as well.  Following the migration guide here helped:

https://tailwindcss.com/docs/upgrade-guide#using-the-upgrade-tool

**Comment by Yuran-Eduardo** [comment]
I am Facing the same issue, using tailwind in React.js. 

<img width="923" alt="Image" src="https://github.com/user-attachments/assets/8059ebe1-2569-4a19-9b3f-8c2d53ef47c7" />

**Comment by Yuran-Eduardo** [comment]
> I am Facing the same issue, using tailwind in React.js.
> 
> <img alt="Image" width="923" src="https://private-user-images.githubusercontent.com/84380815/406613141-8059ebe1-2569-4a19-9b3f-8c2d53ef47c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc3NjY2NTYsIm5iZiI6MTczNzc2NjM1NiwicGF0aCI6Ii84NDM4MDgxNS80MDY2MTMxNDEtODA1OWViZTEtMjU2OS00YTE5LTliM2YtOGMyZDUzZWY0N2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI1VDAwNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiY2Y0OTExMzdjNjBmNzFjMDJhZjYxMTA0NjY0NDhlZDY3OGM3YjA5ODhjNGMwMGVkODVmZTIzNTBkNzE2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VjlfvLSggPhSScVgkCPdI9PfzrG8uATHTtO__HwmezU">

Solve this error by installing it using cli: https://tailwindcss.com/docs/installation/tailwind-cli

**Comment by hitchcliff** [comment]
I solved it by following the documentation and removing `one less file` which is the most important file for me `tailwind.config.js` 

very upsetting.

**Comment by vdegenne** [comment]
> I solved it by following the documentation and removing `one less file` which is the most important file for me `tailwind.config.js`
> 
> very upsetting.

It can't be "most important" since in tw4 you don't need it anymore.

**Comment by PrzemyslawSochon** [comment]
I kept getting errors when trying to manually update from v3 to v4, regardless of that I did. So I decided to use the automatic tool that tailwind team offers here [Using upgrade tool](https://tailwindcss.com/docs/upgrade-guide#using-the-upgrade-tool)

Unfortunately, the tool itself was quirky, but at the end of the day I've managed to run it. Here's how:

The tool only works for Tailwind v3, so I've downgraded the Tailwind package.

However, after running `npx @tailwindcss/upgrade@next` I kept getting:

`Could not determine configuration file for: `./app/globals.css` 
│   Update your stylesheet to use `@config` to specify the correct configuration file 
│   explicitly and then run the upgrade tool again.`

As described, I explicitly added direction to my config file at the top of my globals.css:
`@config "../tailwind.config.ts";`

After that I still kept getting errors about missing directions inside node_modules (!) which is bogus. I worked around it by passing list of files that I want to migrate directly into the command as such:
`npx @tailwindcss/upgrade@next ./app/globals.css`
Depending on your files and their location you'd have to adjust that.After that, the app was fixed.

**Comment by andreipatza** [comment]
Anyone with the same error when using cli from v0.dev?

**Comment by Suryanshu1005** [comment]
So, I was able to fix the error by making below changes:
added this in postcss.config.js file
```
module.exports = {
  plugins: { "@tailwindcss/postcss": {} }
};
```

removed utility, base and component from global.css and instead added
```
@import "tailwindcss";
```

and lastly installed 
```
"@tailwindcss/postcss": "^4.0.0",
```


Hope this helps. Thank you everyone for the responses.

**Comment by zulfiismailovdemiri** [comment]
> So, I was able to fix the error by making below changes: added this in postcss.config.js file
> 
> ```
> module.exports = {
>   plugins: { "@tailwindcss/postcss": {} }
> };
> ```
> 
> removed utility, base and component from global.css and instead added
> 
> ```
> @import "tailwindcss";
> ```
> 
> and lastly installed
> 
> ```
> "@tailwindcss/postcss": "^4.0.0",
> ```
> 
> Hope this helps. Thank you everyone for the responses.

great. just solved as you, using laravel-mix for any project ``` module.exports = {
    plugins: {
        '@tailwindcss/postcss': {},
        autoprefixer: {},
    }
} and on webpack.mix.js: mix.js('src/js/app.js', 'assets/js')
    .postCss('src/css/style.css', 'assets/css', [
        require('@tailwindcss/postcss'),
    ]);```

**Comment by GoulartNogueira** [comment]
**Solved** _(at least on Next.js)_

1. Went back to v3
2. Upgrade to V4 by running: `$ npx @tailwindcss/upgrade@next`

Source:
https://tailwindcss.com/docs/upgrade-guide#using-the-upgrade-tool

**Comment by ms-dosx86** [comment]
I was trying to import `tailwindcss` in my `index.scss` file which was imported in `main.tsx`. It doesn't work.

When I created a separate `index.css` file which imported `tailwindcss` and included it in `index.html` it finally worked.

**Comment by eliotis** [comment]
## **NX Monorepo problems with Angular and upgrade to Tailwind 4**

After following instructions for the Angular upgrade to Tailwind 4.0 I get a bunch of this: 
 
```
[ERROR] Cannot apply unknown utility class: bg-white [plugin angular-sass]

    node_modules/tailwindcss/dist/lib.js:17:296:
      17 │ ...r,{onInvalidCandidate:x=>{throw new Error(`Cannot apply unknown...
         ╵                                    ^

    at onInvalidCandidate (/home/takis/Code/eliotis/node_modules/tailwindcss/dist/lib.js:17:297)
    at ee (/home/takis/Code/eliotis/node_modules/tailwindcss/dist/lib.js:12:116086)
    at /home/takis/Code/eliotis/node_modules/tailwindcss/dist/lib.js:17:260
    at D (/home/takis/Code/eliotis/node_modules/tailwindcss/dist/lib.js:3:3502)
    at D (/home/takis/Code/eliotis/node_modules/tailwindcss/dist/lib.js:3:3742)
    at Ce (/home/takis/Code/eliotis/node_modules/tailwindcss/dist/lib.js:17:150)
    at jr (/home/takis/Code/eliotis/node_modules/tailwindcss/dist/lib.js:33:800)
    at async Ur (/home/takis/Code/eliotis/node_modules/tailwindcss/dist/lib.js:33:1053)
    at async nt (/home/takis/Code/eliotis/node_modules/@tailwindcss/node/dist/index.js:10:3251)
    at async p (/home/takis/Code/eliotis/node_modules/@tailwindcss/postcss/dist/index.js:8:3200)

  This error came from the "onLoad" callback registered here:

    node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.js:125:22:
      125 │                 build.onLoad({ filter: language.fileFilter, names...
```

for many utility classes that previously worked fine. I created the .postcssrc.json file as instructed (would not build without it) What am I missing?

**Comment by MmKargar** [comment]
The solution for me was 
1- `yarn add @tailwindcss/postcss`

2- touch `postcss.config.js` 
```
export default {
    plugins: {
        '@tailwindcss/postcss': {},
        autoprefixer: {},
    },
};
```

**Comment by ikitozen** [comment]
manual route for vue 3

1. package.json 

"devDependencies": {
  "@tailwindcss/postcss": "^4.0.0",
  "tailwindcss": "^4.0.0"
}

2. postcss.config.js (or other...)

module.exports = {
  plugins: {
    '@tailwindcss/postcss': {},
  }
}; 

  
3. asset.css (or your ...)
@import "tailwindcss"; 


4.  main.ts (or your ...)
import { createApp } from 'vue';
import App from './App.vue';
import './assets/tailwind.css';
createApp(App).mount('#app');

**Comment by BarishSarac** [comment]
NextJS Same issue
**Error: It looks like you're trying to use `tailwindcss` directly as a PostCSS plugin. The PostCSS plugin has moved to a separate package, so to continue using Tailwind CSS with PostCSS you'll need to install `@tailwindcss/postcss` and update your PostCSS configuration.**

How's this possible major version release of a package that has millions of weekly download has this big of a problem? crazy

**Comment by igorakkerman** [comment]
In case you came here having this problem with Nuxt:
- Remove `@nuxtjs/tailwindcss` from `modules` in `nuxt.config.ts`
- Uninstall `@nuxtjs/tailwindcss` with your package manager, e.g. `npm uninstall @nuxtjs/tailwindcss`
- Follow the steps in the installation guide for Tailwind with Nuxt: https://tailwindcss.com/docs/installation/framework-guides/nuxt

The Tailwind module for Nuxt is not necessary at this point but might be back in the future:
https://github.com/nuxt-modules/tailwindcss/issues/820

**Comment by BarishSarac** [comment]
If you came here to migrate your project to v4 properly, follow
https://blog.logrocket.com/getting-ready-tailwind-v4/

`npx @tailwindcss/upgrade@next`

does pretty good job

**Comment by rftglyv** [comment]
Just follow this guide https://tailwindcss.com/docs/installation/framework-guides/nextjs
I've created Next app with create-next-app and it created with old version of Tailwind and its config. But Tw is changed so we have to manually update 2 things.

1. `globals.css` tw import

```css
@import "tailwindcss";
```

2. `postcss.config.mjs` file

```mjs
/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
export default config;
```

**Comment by jjwilliams42** [comment]
This can be reproduced by just creating a new Vue project, then following the instructions from the tailwind installation guide (using vite) at https://tailwindcss.com/docs/installation/using-vite. Which guides you to use @tailwindcss/vite (nothing about postcss - this is why I'm confused)

I've created a fresh repo at https://github.com/jjwilliams42/tailwind-issue

I'm using node v23.6.0

I'm new to tailwind. Was creating a greenfield project using vue + vite + tailwind, ran into this error immediately upon using tailwind my first time.

**Comment by wongjn** [comment]
@jjwilliams42 You've made a mistake in `vite.config.js`. You'd want to use the `@tailwindcss/vite` in that file, not `tailwindcss`:

```diff
 import { fileURLToPath, URL } from 'node:url'
-import tailwindcss from 'tailwindcss'
+import tailwindcss from '@tailwindcss/vite'
 import { defineConfig } from 'vite'
```

**Comment by jjwilliams42** [comment]
D'oh! That did it, thank you :)

**Comment by FahadBinHussain** [comment]
> > I am Facing the same issue, using tailwind in React.js.
> > <img alt="Image" width="923" src="https://private-user-images.githubusercontent.com/84380815/406613141-8059ebe1-2569-4a19-9b3f-8c2d53ef47c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc3NjY2NTYsIm5iZiI6MTczNzc2NjM1NiwicGF0aCI6Ii84NDM4MDgxNS80MDY2MTMxNDEtODA1OWViZTEtMjU2OS00YTE5LTliM2YtOGMyZDUzZWY0N2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI1VDAwNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiY2Y0OTExMzdjNjBmNzFjMDJhZjYxMTA0NjY0NDhlZDY3OGM3YjA5ODhjNGMwMGVkODVmZTIzNTBkNzE2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VjlfvLSggPhSScVgkCPdI9PfzrG8uATHTtO__HwmezU">
> 
> Solve this error by installing it using cli: https://tailwindcss.com/docs/installation/tailwind-cli

Worked using cli, Thanks a lot

**Comment by DasminX** [comment]
I've got this error today. The solution was to do the initialization work again for these two paths:
https://tailwindcss.com/docs/installation/using-vite
and then:
https://tailwindcss.com/docs/installation/using-postcss

What's important, creating postcss.config with .mjs extension was crucial for me.
I will defenitely try to reproduce it again tomorrow and confirm these conclusions.

**Comment by jesseagleboy** [comment]
I think the issue for me was that my Astro config file still had the `tailwindcss` package even when I used the `astro add tailwind`. The `integrations` property had Tailwind while a new property of `vite` had the new Tailwind integration.

What it looks like after deleting the Tailwind integration from the `integrations` property:
<img width="352" alt="Image" src="https://github.com/user-attachments/assets/960dd3a0-a2ac-4144-9c82-76fa61386597" />

**Comment by znwhite** [comment]
In Tailwind v4 it looks like there's no more postcss config file, nor tailwind config file for that matter. For example, to add custom colors you put them directly in your main css file:

```
@import "tailwindcss";

@theme {
  --color-ivy: #1c4044;
  --color-moss: #004d49;
  --color-clover: #058466;
  --color-eggshell: #f9f8f3;
}
```

Here's my working vite config:

```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import tailwindcss from "@tailwindcss/vite";

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss()],
});
```

And here are my dependencies:

```
  "dependencies": {
    "@tailwindcss/cli": "^4.0.3",
    "@tailwindcss/postcss": "^4.0.3",
    "@tailwindcss/vite": "^4.0.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^7.1.5"
  },
  "devDependencies": {
    "@eslint/js": "^9.17.0",
    "@types/react": "^18.3.18",
    "@types/react-dom": "^18.3.5",
    "@vitejs/plugin-react": "^4.3.4",
    "@vitejs/plugin-react-swc": "^3.5.0",
    "autoprefixer": "^10.4.20",
    "eslint": "^9.17.0",
    "eslint-plugin-react": "^7.37.2",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-react-refresh": "^0.4.16",
    "globals": "^15.14.0",
    "postcss": "^8.5.1",
    "tailwindcss": "^4.0.3",
    "vite": "^6.0.5"
  }
```

**Comment by DanielOberlechner** [comment]
> In Tailwind v4 it looks like there's no more postcss config file, nor tailwind config file for that matter. For example, to add custom colors you put them directly in your main css file:

Thats not correct.
If you are using vite there is no postcss config.
If you use Angular, NextJS or similar there is one.

In your special case you are right, but as I wrote in the issue in my case there is one.

**Comment by vdegenne** [comment]
I'm pretty sure you still need the tailwindcss config file with Vite (unless you use `@tailwindcss/vite` which I don't use because the default works for me).

Also Vite is using `postcss` in the background of course, just because you don't need the config file doesn't mean it's not there.

**Comment by Jamshaid-aziz121** [comment]
I can resolve it...now

**Comment by FrischSticks** [comment]
I've spent hours on this one and still haven't figured it out :/

Why must it be so hard...

**Comment by philipp-spiess** [comment]
@FrischSticks Ugh, sorry for the frustration. I recommend taking a look at our official getting started guides since it goes into detail about the different packages and how to set up with your build tool: https://tailwindcss.com/docs/installation/using-vite 

What exactly are you trying to do that doesn't work?

**Comment by CallumBee** [comment]
I am a totally green user of Tailwind and this is the first time using it and came across this issue! I am running it with Laravel Jetstream which came with PostCSS installed. I removed all references of it, uninstalled the package etc and that made it all work! Hope this solves the issue for others.

**Comment by fahimrayhan** [comment]
For NextJS, I have changed the tailwindcss version to : `"tailwindcss": "^3.3.0"`, and then installed it (npm i).
Finally I run tailwindcss codemod: `npx @tailwindcss/upgrade@next` and it works

**Comment by AmirMehrabi** [comment]
I have to modify the postcss.config.php and remove this line to resolve the issue:
```
export default {
    plugins: {
        **tailwindcss: {},**
        autoprefixer: {},
    },
};
```
I'm using laravel 11, Tailwildcss 4 and Vite.

**Comment by johurul000** [comment]
I was able to solve the issue in my React app for now

1. **Uninstalling existing packages**:

   ```bash
   npm uninstall autoprefixer postcss tailwindcss
   ```

2. **Installing the required versions**:

   ```bash
   npm install tailwindcss@^3.4.17 postcss@^8.5.0 autoprefixer@^10.4.20
   ```

**Comment by kerrymeso** [comment]
> I was able to solve the issue in my React app for now
> 
> 1. **Uninstalling existing packages**:
>    npm uninstall autoprefixer postcss tailwindcss
> 2. **Installing the previous versions**:
>    npm install tailwindcss@^3.4.17 postcss@^8.5.0 autoprefixer@^10.4.20

this worked

**Comment by woganmay** [comment]
>    npm install tailwindcss@^3.4.17 postcss@^8.5.0 autoprefixer@^10.4.20

Solved on a brand new Laravel install, thanks @johurul000 !

**Comment by mdulc928** [comment]
For anyone using the new Svelte cli, removing the `tailwind.config.js` and the `postcss.config.js` is what helped me. They are no longer needed thankfully.

After killing my dev script and restarting. It was all good again.

**Comment by fahadhassan101** [comment]
`npm i -D @tailwindcss/postcss  `

```
/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
    autoprefixer: {},
  },
};

export default config;
```


I'm working on turbo monorepo, trying to setup the react + vite + tailwind. above settings works for me

**Comment by Akinsola1** [comment]
> I'm using Vite and I just had to delete tailwindcss from my postcss plugins. Everything works fine now.

worked for me

**Comment by nerzid** [comment]
> I was able to solve the issue in my React app for now
> 
> 1. **Uninstalling existing packages**:
>    npm uninstall autoprefixer postcss tailwindcss
> 2. **Installing the previous versions**:
>    npm install tailwindcss@^3.4.17 postcss@^8.5.0 autoprefixer@^10.4.20

This worked for me as well in my NextJS project.


postcss.config.js
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

tailwind.config.js
```
/** @type {import('tailwindcss').Config} */
import {heroui} from "@heroui/react";
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [heroui()]
}
```

**Comment by the-lemonboy** [comment]
I removed the tailwindcss in postcss.config.js: {}
```javascript
export default {
  plugins: {
    // tailwindcss: {},
    autoprefixer: {},
  },
}
```
This problem is solved by introducing tailwindcss in the global style file.
```css
@import url('./tailwindcss.css');
@import "tailwindcss";
```

**Comment by Stuub** [comment]
> I was able to solve the issue in my React app for now
> 
>     1. **Uninstalling existing packages**:
>        npm uninstall autoprefixer postcss tailwindcss
> 
>     2. **Installing the previous versions**:
>        npm install tailwindcss@^3.4.17 postcss@^8.5.0 autoprefixer@^10.4.20

This worked perfectly thank you for saving me from wasting another hour on this lol

**Comment by roicort** [comment]
> For NextJS, I have changed the tailwindcss version to : `"tailwindcss": "^3.3.0"`, and then installed it (npm i). Finally I run tailwindcss codemod: `npx @tailwindcss/upgrade@next` and it works

This actually worked, thanks!!!

**Comment by 6farer** [comment]
> [@Mearman](https://github.com/Mearman) Have a look at this: https://tailwindcss.com/docs/installation/framework-guides/nextjs

* Next.js * FOLLOW THIS. There's no need to downgrade or remove anything.

1. Run `npm install -D tailwindcss @tailwindcss/postcss postcss`
2. 
    ```javascript
    const config = {
      plugins: {
        "@tailwindcss/postcss": {},
      },
    };
    export default config;
3. `@import "tailwindcss";` to your global.css

Do step 3. That's probably what you missed.

**Comment by JayDoesPHP** [comment]
> > I was able to solve the issue in my React app for now
> > ```
> > 1. **Uninstalling existing packages**:
> >    npm uninstall autoprefixer postcss tailwindcss
> > 
> > 2. **Installing the previous versions**:
> >    npm install tailwindcss@^3.4.17 postcss@^8.5.0 autoprefixer@^10.4.20
> > ```
> 
> This worked perfectly thank you for saving me from wasting another hour on this lol

this worked!!!

**Comment by tobiasBora** [comment]
For those that have weird style breaks, note that v4 **does not use `tailwind.config.ts` anymore**, but everything should go to `global.css` https://tailwindcss.com/blog/tailwindcss-v4#css-first-configuration

**Comment by ChibuikeA11** [comment]
> "Everything's working finally going to bed!" _wake up the next day_ _pour some coffee_ _sit on desk_ _press enter_ **Big explosion** "Aaah don't you like being a web dev?"

Literally, just happened to me and its same stupid postcssconfig issue

**Comment by uzmaI** [comment]
> https://tailwindcss.com/docs/installation/framework-guides/angular
> 
> You should create for Angular a .postcssrc.json with the following content: { "plugins": { "@tailwindcss/postcss": {} } }
> 
> Then it worked for me...
> 
> [@Mearman](https://github.com/Mearman) Have a look at this: https://tailwindcss.com/docs/installation/framework-guides/nextjs

solved for me

**Comment by pranay-janjarla** [comment]
this video helps! 
[https://www.youtube.com/watch?v=bupetqS1SMU]

**Comment by dmtr-igntv** [comment]
Hi there! I faced with an issue where I couldn't set up my base theme colors in a Nuxt 3 project. So, my config now looks like:

```
/* nuxt.config.ts */

import tailwindcss from "@tailwindcss/vite";

export default defineNuxtConfig({
   css: ["@/assets/css/global.css"],
   vite: {
    plugins: [
      tailwindcss(),
    ],
  },
})
```
https://tailwindcss.com/docs/installation/framework-guides/nuxt

```
/* assets/css/global.css */

@import "tailwindcss";

@theme {
    --color-primary: #1E2A3A;
    --color-accent: #C4924D;
    --color-background: #FFFFFF;
    --color-text: #1E2A3A;
    --color-muted: #4A5568;
}
```
https://tailwindcss.com/docs/theme

**Comment by scherddel** [comment]
> Hi there! I faced with an issue where I couldn't set up my base theme colors in a Nuxt 3 project. So, my config now looks like:
> 
> ```
> /* nuxt.config.ts */
> 
> import tailwindcss from "@tailwindcss/vite";
> 
> export default defineNuxtConfig({
>    css: ["@/assets/css/global.css"],
>    vite: {
>     plugins: [
>       tailwindcss(),
>     ],
>   },
> })
> ```
> 
> https://tailwindcss.com/docs/installation/framework-guides/nuxt
> 
> ```
> /* assets/css/global.css */
> 
> @import "tailwindcss";
> 
> @theme {
>     --color-primary: #1E2A3A;
>     --color-accent: #C4924D;
>     --color-background: #FFFFFF;
>     --color-text: #1E2A3A;
>     --color-muted: #4A5568;
> }
> ```
> 
> https://tailwindcss.com/docs/theme

Are you sure thus works for your nuxt3 project and version 4 of tailwind? I am really struggling to resolve the issue. Can you share your full setup? (package.json)

**Comment by mommaroodles** [comment]
@JayDoesPHP  Thank you! that worked for me too - so clearly a problem with the latest release. In my stack its only tailwind now that is outdated - everything else runs at the latest - NextJS, React and everything else

**Comment by tag8x** [comment]
It seems logical to me to revert to the old version.

Solved this problem quickly:
https://youtu.be/Uvemk9Q8_34?si=pBCEQZCIl-J6bl07

**Comment by Aternix12** [comment]
I'm having trouble with the upgrade to v4 with PrimeUI in Nuxt3. The only thing that has worked is reverting to the previous tailwind version...

**Comment by mikob** [comment]
Use the `npx @tailwindcss/upgrade` for v3 to v4 instead of upgrading via pnpm/yarn/npm to avoid this issue and more.

**Comment by TomasHubelbauer** [comment]
I just faced this issue updating a Next 15 project to use all latest dependencies, that includes Tailwind 4 and for folks who are not going to read a hundred posts and are just randomly trying suggestions to see what works for them, this is what worked in my case (vanilla Next 15 app with no extra PostCSS config or stuff):

https://github.com/tailwindlabs/tailwindcss/discussions/15764#discussioncomment-12188959

**Comment by deadcoder0904** [comment]
> Use the `npx @tailwindcss/upgrade` for v3 to v4 instead of upgrading via pnpm/yarn/npm to avoid this issue and more.

This worked. Downgraded to v3 & then used this command with `bunx`.

**Comment by shno784** [comment]
For those using nextjs this worked for me https://tailwindcss.com/docs/installation/framework-guides/nextjs

**Comment by YannickNCode** [comment]
You just have to follow the tailwind doc.
`npm install tailwindcss @tailwindcss/postcss postcss`

Rename postcss.config.js to postcss.config.mjs

Replace into postcss.config.mjs
`module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
To
`const config = {
    plugins: {
        "@tailwindcss/postcss": {},
    },
};
export default config;`

And replace into globals.css
`@tailwind base;
*@tailwind components;
@tailwind utilities;`

To
`@import "tailwindcss";`

**Comment by Skarvion** [comment]
> For those using nextjs this worked for me https://tailwindcss.com/docs/installation/framework-guides/nextjs

Solution for NextJS: I got it working, but I had to tweak it more than what that document shows. It's wrong. If you create a new NextJS project that uses TypeScript using `npx create-next-app@latest`, you'll get the following `postcss.config.mjs` file:

```ts
const config = {
  plugins: ["@tailwindcss/postcss"],
};
export default config;
```

Pay attention that plugins property is an ARRAY. Also, this is equally important, the file type must be `.mjs`, instead of regular `.js`.

Hopefully an admin can fix that document

**Comment by karldivad** [comment]
This works on Tailwind 4.1.3:

```
@import 'tailwindcss';
@config "../tailwind.config.js";
```

The `@config` line is optional, but using it works better than inline (e.g., inline `prefix(tw)` doesn't work on Sass)

You may also need to enable optimization by adding `optimize: true` to **Minify the result** option in your `postcss.config.js`:

```
module.exports = {
  plugins: {
    '@tailwindcss/postcss': {
      base: `${__dirname}/../..`,
      optimize: true,
    },
    autoprefixer: {},
  },
};
```
The `base` line is optional, because I need to load from parent directories too.

**Comment by ragnarbull** [comment]
> You just have to follow the tailwind doc. `npm install tailwindcss @tailwindcss/postcss postcss`
> 
> Rename postcss.config.js to postcss.config.mjs
> 
> Replace into postcss.config.mjs `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {}, }, } ` To `const config = { plugins: { "@tailwindcss/postcss": {}, }, }; export default config;`
> 
> And replace into globals.css `@tailwind base; *@tailwind components; @tailwind utilities;`
> 
> To `@import "tailwindcss";`

thanks!!!

**Comment by benounnas** [comment]
i created [a pull request](https://github.com/tailwindlabs/tailwindcss.com/pull/2207) to be mentioned in the doc specifically, i am always coming back here to fix it, it's based on all answers here and ironically it's mentioned in the upgrade guide

**Comment by ExxTheDev** [comment]
For me postcss.config.mjs only gets rid of the error but only shadow-lg class work, all the other ones don't get applied

<div class="bg-purple-500 text-red-500 p-4 rounded-lg shadow-lg underline">
            Tailwind with SCSS works!
        </div>

**Comment by ExxTheDev** [comment]
`<div class="bg-purple-500 text-red-500 p-4 rounded-lg shadow-lg underline">
            Tailwind with SCSS works!
        </div>`

**Comment by mhagnumdw** [comment]
I'm on Angular 19 migrating from tailwind v3 to v4 and I only had the following error in the tests: `ng test`. It worked fine on `ng serve` and `ng build`.
```
An unhandled exception occurred: It looks like you're trying to use `tailwindcss` directly as a PostCSS plugin. The PostCSS plugin has moved to a separate package, so to continue using Tailwind CSS with PostCSS you'll need to install `@tailwindcss/postcss` and update your PostCSS configuration.
```
After removing `tailwind.config.js` everything was ok. Leaving it here to help someone.

ps: can someone explain?!

**Comment by wongjn** [comment]
Angular's Webpack config [incorrectly loads the `tailwindcss` package into PostCSS plugins when you have a `tailwind.config.js` in the project](https://github.com/angular/angular-cli/blob/cf31d19621995321426e87f6f6003143fcee0180/packages/angular_devkit/build_angular/src/tools/webpack/configs/styles.ts#L82-L98). This then causes this error.

**Comment by iampato** [comment]
If you are using `nx` and `nextjs`

in `postcss.config.js`
Change from
```js
const { join } = require('path');

// Note: If you use library-specific PostCSS/Tailwind configuration then you should remove the `postcssConfig` build
// option from your application's configuration (i.e. project.json).
//
// See: https://nx.dev/guides/using-tailwind-css-in-react#step-4:-applying-configuration-to-libraries

module.exports = {
  plugins: {
    tailwindcss: {
       config: join(__dirname, 'tailwind.config.js'),
    },
    autoprefixer: {},
  },
};
```

to
```js
const { join } = require('path');

// Note: If you use library-specific PostCSS/Tailwind configuration then you should remove the `postcssConfig` build
// option from your application's configuration (i.e. project.json).
//
// See: https://nx.dev/guides/using-tailwind-css-in-react#step-4:-applying-configuration-to-libraries

module.exports = {
  plugins: {
    '@tailwindcss/postcss': {
      optimize: {
        minify: true,
      },
      content: [
      ]
    },
    autoprefixer: {},
  },
};


```

**Comment by regenrek** [comment]
Any idea why we still need a `postcss.config.ts` for tanstack starter even I have added the `vite.config.ts`

```
import { defineConfig, mergeConfig } from 'vite';
import { tanstackViteConfig } from '@tanstack/config/vite';
import tailwindcss from "@tailwindcss/vite";
import path from "path"

const config = defineConfig({
  plugins: [tailwindcss()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
      "~": path.resolve(__dirname, "./src"),
    },
  },
});

export default mergeConfig(
  config,
  tanstackViteConfig({
    entry: './src/index.ts',
    srcDir: './src',
  }),
);
```

**Comment by wongjn** [comment]
I don't think you need a PostCSS config if you are using Vite.

**Comment by regenrek** [comment]
> I don't think you need a PostCSS config if you are using Vite.

Yes, that's what i think too. but it only works like this. As soon I remove the postcss file it doesn't work anymore.

Rest of the minimal code:
```
import appCss from "@/index.css?url"

links: [
      {
        rel: 'stylesheet',
        href: appCss,
      },
]
```

index.css
```
@import "tailwindcss";

...
```

**Comment by nitinkanade** [comment]
I faced a similar issue when using Tailwind CSS as a PostCSS plugin and found a solution that worked for me.
I have documented the detailed steps here: [How to fix issues when using Tailwind CSS as a PostCSS plugin](https://blog.ni18.in/how-to-fix-issues-when-using-tailwind-css-as-a-postcss-plugin-in-your-project/).

Hope this helps others facing the same problem! 🚀

**Comment by Ayomidotun11** [comment]
"Module not found: Can't resolve 'tailwindcss/version.js'
Module not found: Can't resolve 'tailwindcss/version.js'
> 1 | import version from 'tailwindcss/version.js';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 1 | import version from 'tailwindcss/version.js';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |
  2 |
  3 | function getTailwindVersion() {
  3 | function getTailwindVersion() {
  4 |   try {
"

I get this error when my  flowbite-react package is trying to import tailwindcss/version.js, but the file is missing. This project is a nextsjs (15.3.1) web app project. please who can help with this?

**Comment by wongjn** [comment]
> Thanks [@DanielOberlechner](https://github.com/DanielOberlechner) In angular creating a .postcssrc.json instead of postcss.config.js with the following content worked for me at least changed the error😁:
> 
> `{ "plugins": { "@tailwindcss/postcss": {} } }`
> 
> now i'm getting:
> 
> `▲ [WARNING] Deprecation [plugin angular-sass]
> 
> ```
> src/app/modules/features/account-config/...-.component.scss:4:8:
>   4 │ @import "src/assets/css/tailwindcss/variables.scss";
>     ╵`
> ```

See [the warning in the Sass docs](https://sass-lang.com/documentation/at-rules/import/):

> As of Dart Sass 1.80.0, the @import rule is [deprecated](https://sass-lang.com/documentation/breaking-changes/import) and will be removed from the language in Dart Sass 3.0.0. Prefer the [@use rule](https://sass-lang.com/documentation/at-rules/use) instead.

Also tangentially [from the Tailwind docs](https://tailwindcss.com/docs/compatibility#sass-less-and-stylus):

> Tailwind CSS v4.0 is a full-featured CSS build tool designed for a specific workflow, and is not designed to be used with CSS preprocessors like Sass, Less, or Stylus.

**Comment by TanbirRamim** [comment]
"Error: It looks like you're trying to use `tailwindcss` directly as a PostCSS plugin. The PostCSS plugin has moved to a separate package, so to continue using Tailwind CSS with PostCSS you'll need to install `@tailwindcss/postcss` and update your PostCSS configuration." 

I have updated my configuration, still seems like the problem is not going away; stuck here for hours. any feedback?

**Comment by wongjn** [comment]
@TanbirRamim consider providing a git repo that reproduces the unexpected behavior.

**Comment by Hamza-Bik** [comment]
Try to Remove the node module folder and install it again or remove just the tailwindcss folder

**Comment by TanbirRamim** [comment]
@wongjn have a look please, https://github.com/TanbirRamim/Merchandise-Dashboard

**Comment by EliotAndres** [comment]
I fixed the issue by removing the tailwind.config.js file. When present and when not using Vite, I was getting the error even after updating to the standalone `@tailwindcss/postcss` plugin

**Comment by dlukt** [comment]
@oscarteg what does that mean? How do you "remove from integrations"?

**Comment by ngrcode** [comment]
i had this issue bcs i had removed yarn.lock
i runed yarn 
and return yarn.lock 
then it works.

**Comment by FilipKohout** [comment]
Had the same issue. I downgraded from tailwind ^4.0.0 and now it works.

**Comment by djolekrstic** [comment]
npm install -D @tailwindcss/postcss autoprefixer tailwindcss-primeui @tailwindcss/forms

.postcssrc.json
`{
  "plugins": {
    "@tailwindcss/postcss": {},
    "tailwindcss-primeui": {},
    "@tailwindcss/forms": {}
  }
}
`
styles.css
`@import 'tailwindcss';
@plugin "tailwindcss-primeui";
`
NX angular-monorepo, esbuild

**Comment by DanielOberlechner** [comment]
> [@DanielOberlechner](https://github.com/DanielOberlechner) Excuse me? Are you a developer? Can you review the [community guideline](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines) before replying? (Be welcoming and open-minded and be RESPECTFUL)
>

I've said  it the most respectful way I could. we have now 100+ answers to this problem. some are using vite, some angular, some nextJS. There is no clear solution for this right now. No one new will find here a solution to his problem in my opinion. Then you start suddenly speaking of tailwind3 vs tailwind4 even though the main reason to create this issue was upgrading from v3 to v4.

> I believe everyone who replied here did so, to share helpful tips and to help anyone in need. This is what you should be HONORED! The reason I replied to the comments is that I searched on Google when I was struggling, and this GitHub link popped up and contributed to my final solution, so I share mine here, hopefully to help anyone.
> 
> If you don't want people to see yours, change it to private or delete it; otherwise, staying in this community means you need to be respectful and helpful and at least KIND!

I can't delete this issue it was also closed a few days later after it has been opened. I try also to help others to develop simpler or help them fix bugs, but this issue here what I created just got messy. Every 2-3 days someone posts it works or it doesn't work and that makes no sense in my opinion. First when I created this issue there was no direct framework upgrade docs. These exist now and are very simple.

Sorry if I offended you, but you got to be realistic if your comment will help anybody or not. And I personally don't think a new comment on a 150+ post issue is doing any good. But thats just my opinion.

**Comment by gaoshunpeng** [comment]
@S1Y333 Thank you, although I still can't use v4, but through your answer, I can use v3 normally, which is very helpful to me.

**Comment by gterminator** [comment]
just adding it in v4 doesn't make the library better @DanielOberlechner. Just fyi.
