### ISSUE TITLE
TypeError: getProcessedPlugins is not a function

### ISSUE THREAD

**Issue by GregSitholeEntrostat** [tailwindlabs/tailwindcss#2810]
### Describe the problem:

Upgraded from TailwindCSS 1.9.6 to 2.0.1 for my angular project following the instructions on their website. I had previously used the following guide: https://notiz.dev/blog/angular-10-with-tailwindcss#setup to Install the previous version and that worked before.

Please see error below:

```
ERROR in Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: getProcessedPlugins is not a function
    at /home/greg/angular-website/frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:71:83
    at LazyResult.runOnRoot (/home/greg/angular-website/frontend/node_modules/postcss/lib/lazy-result.js:276:16)
    at LazyResult.runAsync (/home/greg/angular-website/frontend/node_modules/postcss/lib/lazy-result.js:328:26)
    at async Object.loader (/home/greg/angular-website/frontend/node_modules/postcss-loader/dist/index.js:94:14)

ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--13-3!./node_modules/sass-loader/dist/cjs.js??ref--13-4!./node_modules/postcss-loader/dist/cjs.js??ref--17!./src/styles.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: getProcessedPlugins is not a function
    at /home/greg/angular-website/frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:71:83
    at LazyResult.runOnRoot (/home/greg/angular-website/frontend/node_modules/postcss/lib/lazy-result.js:276:16)
    at LazyResult.runAsync (/home/greg/angular-website/frontend/node_modules/postcss/lib/lazy-result.js:328:26)
    at async Object.loader (/home/greg/angular-website/frontend/node_modules/postcss-loader/dist/index.js:94:14)

```

**Comment by alexcroox** [comment]
I too am getting this, I'm using the PostCSS 7 compatibility build

**Comment by GregSitholeEntrostat** [comment]
@alexcroox I managed to fix it on my end. 

What I did was I removed the existing `tailwind.config.js` and just ran the command `npx tailwindcss init --full`, then I just applied the custom configurations that I did to it. I'm going to close the issue since I fixed my original issue

**Comment by SimonPrague** [comment]
I have the same issue and was not able to resolve it yet. 
Can it be due to the use of plugins?

  plugins: [
    require('@tailwindcss/ui'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],

**Comment by alexcroox** [comment]
@GregSitholeEntrostat what was the diff on your tailwind.config.js? Perhaps there is something missing in the upgrade guide? Could you re-open as it seems others are hitting this issue and we've not got to the fix yet.

**Comment by GregSitholeEntrostat** [comment]
@alexcroox There's quite a bit of change. Here's a link to their latest version https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js

@SimonPrague I'm not too sure, I'm not familiar with those plugins and currently not using any! Have you tried to see what happens when you remove the plugins?

**Comment by SimonPrague** [comment]
It breaks the same even with removing those plugins :(

**Comment by SimonPrague** [comment]
Ok I removed the UI plugin as it seems no longer required for TailwindUI. But I get this error instead:

```
error  in ./src/components/profile/widgets/***.vue?vue&type=style&index=0&id=71d401a6&scoped=true&lang=postcss

Module build failed (from ./node_modules/.pnpm/postcss-loader@3.0.0/node_modules/postcss-loader/src/index.js):
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Object.module.exports [as typography] (/home/***/client/node_modules/.pnpm/@tailwindcss/typography@0.3.1_tailwindcss@2.0.1/node_modules/@tailwindcss/typography/src/styles.js:1076:13)
    at /home/***/client/node_modules/.pnpm/tailwindcss@2.0.1_01b244ddc5034529ac96d3fe28ec275b/node_modules/tailwindcss/lib/util/resolveConfig.js:135:65
    at Array.reduce (<anonymous>)
    at resolveFunctionKeys (/home/***/client/node_modules/.pnpm/tailwindcss@2.0.1_01b244ddc5034529ac96d3fe28ec275b/node_modules/tailwindcss/lib/util/resolveConfig.js:133:30)
    at resolveConfig (/home/***/client/node_modules/.pnpm/tailwindcss@2.0.1_01b244ddc5034529ac96d3fe28ec275b/node_modules/tailwindcss/lib/util/resolveConfig.js:270:12)
    at /home/***/client/node_modules/.pnpm/tailwindcss@2.0.1_01b244ddc5034529ac96d3fe28ec275b/node_modules/tailwindcss/lib/index.js:75:37
    at /home/***/client/node_modules/.pnpm/tailwindcss@2.0.1_01b244ddc5034529ac96d3fe28ec275b/node_modules/tailwindcss/lib/processTailwindFeatures.js:50:20
    at LazyResult.run (/home/***/client/node_modules/.pnpm/postcss@7.0.35/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/home/***/client/node_modules/.pnpm/postcss@7.0.35/node_modules/postcss/lib/lazy-result.js:212:26)
    at LazyResult.asyncTick (/home/***/client/node_modules/.pnpm/postcss@7.0.35/node_modules/postcss/lib/lazy-result.js:225:14)
    at /home/***/client/node_modules/.pnpm/postcss@7.0.35/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (/home/***/client/node_modules/.pnpm/postcss@7.0.35/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (/home/***/client/node_modules/.pnpm/postcss@7.0.35/node_modules/postcss/lib/lazy-result.js:131:17)
    at /home/***/client/node_modules/.pnpm/postcss-loader@3.0.0/node_modules/postcss-loader/src/index.js:142:8
```

**Comment by SimonPrague** [comment]
I guess that could be related to #861

**Comment by creimers** [comment]
I managed solving the problem like so: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by SimonPrague** [comment]
That did not help. Is it possible due to the change in colors? I was using both gray and cool-gray and it seems there were some changes...

**Comment by SimonPrague** [comment]
Ok I've added alias for cool-gray and I'm back to the ```TypeError: getProcessedPlugins is not a function``` and even with the compat build :(

**Comment by SimonPrague** [comment]
OK I have no solution so far. It might be because of: vue cli and postcss loader 
 https://github.com/vuejs/vue-cli/issues/6064

**Comment by SimonPrague** [comment]
Anyone got Tailwind 2 working with Typescript & Vue Cli & Vue 3, heh?

**Comment by lesteak** [comment]
I also had this issue. did you follow the [upgrade guide](https://tailwindcss.com/docs/upgrading-to-v2)? 

Specifically, did you upgrade postcss?
`npm install tailwindcss@latest postcss@latest autoprefixer@latest`

**Comment by SimonPrague** [comment]
Yep, I followed these instructions. I tried both **latest** and **comp** versions. Still the same problem.

**Comment by IgorNoskov** [comment]
Hey guys! I have the same problem. I've been trying to migrate to tailwind 2 for hours now.

**Comment by IgorNoskov** [comment]
Whatever I do, I get a `TypeError: getProcessedPlugins is not a function.`

**Comment by CreateSean** [comment]
> What I did was I removed the existing `tailwind.config.js` and just ran the command `npx tailwindcss init --full`, then I just applied the custom configurations that I did to it. I'm going to close the issue since I fixed my original issue

I tried that but still get errors

```ERROR in ./src/css/app.css
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: getProcessedPlugins is not a function
    at D:\sites\Land-Development\node_modules\tailwindcss\lib\processTailwindFeatures.js:71:83
    at LazyResult.run (D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:288:14)
    at LazyResult.asyncTick (D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:212:26)
    at LazyResult.asyncTick (D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:225:14)
    at D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:250:23)
    at LazyResult.then (D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:131:17)
    at Promise.resolve.then.then (D:\sites\Land-Development\node_modules\postcss-loader\src\index.js:142:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at runLoaders (D:\sites\Land-Development\node_modules\webpack\lib\NormalModule.js:316:20)
    at D:\sites\Land-Development\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\sites\Land-Development\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\sites\Land-Development\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (D:\sites\Land-Development\node_modules\postcss-loader\src\index.js:208:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 @ ./src/css/app.css

ERROR in ./src/css/app.css (./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/src??postcss0!./src/css/app.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):    
TypeError: Object.entries(...).flatMap is not a function
    at flattenColorPalette (D:\sites\Land-Development\node_modules\tailwindcss\lib\util\flattenColorPalette.js:8:83)
    at D:\sites\Land-Development\node_modules\tailwindcss\lib\plugins\divideColor.js:27:53
    at plugins.forEach.plugin (D:\sites\Land-Development\node_modules\tailwindcss\lib\util\processPlugins.js:69:5)
    at Array.forEach (<anonymous>)
    at _default (D:\sites\Land-Development\node_modules\tailwindcss\lib\util\processPlugins.js:63:11)
    at D:\sites\Land-Development\node_modules\tailwindcss\lib\processTailwindFeatures.js:60:54
    at LazyResult.run (D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:288:14)
    at LazyResult.asyncTick (D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:212:26)
    at LazyResult.asyncTick (D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:225:14)
    at D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:250:23)
    at LazyResult.then (D:\sites\Land-Development\node_modules\postcss\lib\lazy-result.js:131:17)
    at Promise.resolve.then.then (D:\sites\Land-Development\node_modules\postcss-loader\src\index.js:142:8)
 @ ./src/css/app.css 2:14-142```

**Comment by ThreeScreenStudios** [comment]
I was able to get Tailwind 2 and Vue 2 w/ Cli to work with the compatibility build - currently I believe Vue Cli uses an old version of postcss-loader and thus does not support postcss 8. Hopefully they'll update it in the future (added a request [here](https://github.com/vuejs/vue-cli/issues/6064#issuecomment-730055397)).

Steps I took:

1. Remove tailwind npm package, install `tailwindcss@compat`
2. Removed `require('@tailwindcss/ui')` from plugins in tailwind.config.js, add `require('@tailwindcss/forms')` (there will be styling changes needed, like type="text" required for all plain text inputs)
3. Check to see if any other plugins require postcss 8 (latest `postcss-nested` does for example), roll back those packages to an earlier version 
4. Updated custom color theme in tailwind.config.js (syntax changed a bit, see [here](https://tailwindcss.com/docs/customizing-colors#extending-the-defaults)), also need to add in things like white and transparent if you used those.
4. Run yarn/npm run serve, fix any styling compat errors, should hopefully run after that!

**Comment by audn** [comment]
Hmm.. I had the same error, but fixed it by just fooling around. Try to copy my settings?

This is a pretty big deal too, read the thingy: https://tailwindcss.com/docs/upgrading-to-v1#1-update-tailwind

`let colors = require('tailwindcss/colors');

module.exports = {
  theme: {
    inset: {
      '1/2': '50%',
      '-5': '-5px',
      '-10': '-10px',
      '-15': '-15px',
      '-55': '-55%;',
      '-8': '-32px',
      114: '114px',
      96: '96px',
      0: 0,
      90: '90px',
      80: '80px',
    },
    extend: {
      margin: {
        none: 'initial',
        26: '7rem',
      },
      maxWidth: {
        card: '410px',
      },
      minWidth: {
        card: '344px',
      },
      height: {
        card: '200px',
        priceContent: '234px',
      },
      width: {
        pricing: '335px',
        245: '245px',
        280: '280px',
        345: '345px',
        hr: '200px',
      },
      colors,
      fontFamily: {
        sans: ['proxima-soft', 'sans-serif'],
      },
    },
  },
  variants: {
    textColor: ['responsive', 'hover', 'focus', 'group-hover'],
    textDecoration: ['group-hover'],
    minWidth: ['responsive'],
    opacity: ['group-hover'],
    backgroundColor: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundOpacity: ['responsive', 'hover', 'focus'],
  },
  plugins: [
    // ...
  ],
};
`

**Comment by adamwathan** [comment]
Can someone publish a GitHub repo that reproduces the issue? I suspect it will be fixed by switching to the new compatibility build:

```
npm uninstall tailwindcss postcss autoprefixer
npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
```

The issue we have been seeing is that `npm install tailwindcss@compat` installs `^2.0.1-compat` which also matches `2.0.1` which was causing the wrong version to be installed in some situations.

More details here: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by CreateSean** [comment]
@adamwathan I did run the compatibility build you linked to and still get errors.

**Comment by LawJolla** [comment]
I don't know if this is related... 

I'm running NextJS I had similar issues for hours (`getProcessedPlugins` and `tailwindcss/plugins`).  Following some advice in this thread, I started from a clean config which compiled.  I started incrementally adding my config back until I ended up with my old config.  But it now works / compiles.

It sounds like something is cached somewhere.

**Comment by seankndy** [comment]
@LawJolla when you say you started from a clean config, are you referring to just the `tailwind.config.js` or did you do other things to start fresh?

**Comment by seankndy** [comment]
I setup a fresh new project and installed my css/js deps along with tailwindcss 2.0.1 and it built fine.  After banging my head on it for a while I removed `node_modules/tailwindcss` from the project that was failing to build with `getProcessedPlugins` errors and copied the `node_modules/tailwindcss` from my other fresh project that was working and now my project is building...

**Comment by CreateSean** [comment]
I nuked my node_modules folder I also ran `npm clear cache --force` and tried yet again to get the compatibility build to run and it still fails.

**Comment by seankndy** [comment]
It appears the issue is that the tailwindcss package installed under my node_modules (`./node_modules/tailwindcss/node_modules`) has the `postcss` package installed under it at version 7.0.32.  I am assuming this serves as an override to my "root" postcss package which is installed at version 8.1.8.   Removing `node_modules/tailwindcss/node_modules/postcss` solves the problem and my project now builds.

Perhaps someone here understands why tailwindcss is including that older postcss dep into itself and how to permanently fix this?

**Comment by keljtanoski** [comment]
Check your nodejs version (node -v) , I had v10.19.0, then made global update to v14.15.1, using vue-cli with the following dependencies 
`"dependencies": {
    "autoprefixer": "^9.8.6",
    "core-js": "^3.6.5",
    "postcss": "^7.0.35",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.1",
    "vue": "^2.6.11",
    "vue-router": "^3.4.9"
  },`

After updating node and running npm run serve I was able to build the tailwind under vue-cli

postcss.config.js
`module.exports = {
    plugins: [
        require('tailwindcss'),
        require('autoprefixer'),
    ]
}`

tailwind.config.js
`module.exports = {
  purge: { content: ['./public/**/*.html', './src/**/*.vue'] },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
`

**Comment by seankndy** [comment]
@keljtanoski I am at v14.15.1 already.

**Comment by focux** [comment]
I'm having the same bug and I'm running Next.js, could it be related to that?

**Comment by seankndy** [comment]
> Can someone publish a GitHub repo that reproduces the issue? I suspect it will be fixed by switching to the new compatibility build:
> 
> ```
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```
> 
> The issue we have been seeing is that `npm install tailwindcss@compat` installs `^2.0.1-compat` which also matches `2.0.1` which was causing the wrong version to be installed in some situations.
> 
> More details here: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

Here is a diagnostic repo that I am having the issue on: https://github.com/seankndy/tailwindcss2-break

Steps to reproduce:
`
$ git clone git@github.com:seankndy/tailwindcss2-break.git
$ cd tailwindcss2-break
$ npm install
$ npm run dev
`

**Comment by CreateSean** [comment]
> Check your nodejs version (node -v) , I had v10.19.0, then made global update to v14.15.1,

checked and I was on 10.15.3

I then installed NVM and added node 14.15.1 and this issue is resolved for me. Though I have other ones now.

**Comment by amrography** [comment]
It's node issue https://github.com/notiz-dev/ngx-tailwind/issues/9#issuecomment-730414698

**Comment by focux** [comment]
It's not a Node issue. I'm on Node 14 and I'm still having issues. For some reason, if I remove all the plugins from the Tailwind config object–which are Tailwind plugins—it works well.

**Comment by miguelbui** [comment]
I try update node version and evething work. I used bellow steps

- Upgrade node and lastest version of packages

`nvm use v14.6.0`
`npm clear cache --force`
`npm install tailwindcss@latest postcss@latest autoprefixer@latest`

- And build it
`npx tailwindcss build css/tailwind.css -o public/css/tailwind.css`

**Comment by SimonPrague** [comment]
I tried all the trick above. Still getting the same error. On both **compat** and **latest** versions. I inspected the package lock file and it seems it has the correct lower version on the compat build.

**Comment by seankndy** [comment]
Can anyone clone https://github.com/seankndy/tailwindcss2-break and try npm install + npm run dev and tell me if it works for them and if so what versions they’re running?  It does not work on either of my machines.

I am already on the latest stable version of node and I cannot get the project to build without removing postcss v7 from tailwind's inner dependencies.

Also what’s interesting is when I created the tailwindcss2-break project and started adding node packages and re-building iteratively I was never able to get it to fail.  But somewhere along the way I decided to nuke node_modules and let it rebuild from scratch and that is when it broke.  So I believe it is some sort of dependency graph issue that’s a bit of a moving target to trigger and reproduce.

**Comment by ThreeScreenStudios** [comment]
> Can anyone clone https://github.com/seankndy/tailwindcss2-break and try npm install + npm run dev and tell me if it works for them and if so what versions they’re running? It does not work on either of my machines.
> 
> I am already on the latest stable version of node and I cannot get the project to build without removing postcss v7 from tailwind's inner dependencies.
> 
> Also what’s interesting is when I created the tailwindcss2-break project and started adding node packages and re-building iteratively I was never able to get it to fail. But somewhere along the way I decided to nuke node_modules and let it rebuild from scratch and that is when it broke. So I believe it is some sort of dependency graph issue that’s a bit of a moving target to trigger and reproduce.

I was able to reproduce the issue by cloning your repo - however I think the issue is that you are not using the compat build of tailwind.

I performed `npm remove tailwindcss` and `npm remove postcss` followed by `npm install tailwindcss@npm:@tailwindcss/postcss7-compat` and the project ran after that.

**Comment by seankndy** [comment]
@ThreeScreenStudios thank you!  I tried the compat packages early on and it was failing to build still as others have said as well, but I followed your procedure of removing and re-installing and I'm green again.  Thank you.

**Comment by michalhudecek** [comment]
In my case this was solved by updating node from 10.22.0 to 14.15.1.

I thought I already did that before but I made a mistake in WSL 2 in Windows when updating it the first time.

**Comment by adamwathan** [comment]
Sorry for the hassle here folks, the latest instructions on the website should resolve these issues:

https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

If you're using the typography plugin you'll want to read the release notes there as well:

https://github.com/tailwindlabs/tailwindcss-typography/releases/tag/v0.3.0

If anyone is still running into issues with these updates feel free to open a new issue.

**Comment by Hesesses** [comment]
Had the same problem and updated node to stable version: https://medium.com/macoclock/update-your-node-js-on-your-mac-in-2020-948948c1ffb2

Everything worked after that

**Comment by dinoluck** [comment]
Had the same problem, used the compat build (uninstall, then install compat), got this getProcessedPlugins error, then updated node to stable, now I'm getting:

`ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: value.charCodeAt is not a function`

**Comment by scottyzen** [comment]
This worked for me. Along with adding a .nvmrc file to change Node to v12
```
npm uninstall tailwindcss postcss autoprefixer
npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
```

**Comment by SimonPrague** [comment]
> Sorry for the hassle here folks, the latest instructions on the website should resolve these issues:
> 
> https://tailwindcss.com/docs/installation#post-css-7-compatibility-build
> 
> If you're using the typography plugin you'll want to read the release notes there as well:
> 
> https://github.com/tailwindlabs/tailwindcss-typography/releases/tag/v0.3.0
> 
> If anyone is still running into issues with these updates feel free to open a new issue.

I'm sorry. I followed all the instructions and it still fails. I tried so many different things but this is not a solution yet.

**Comment by adamwathan** [comment]
Please open a new issue that includes an actual GitHub repository, you are missing the most important information we need for troubleshooting which is your package.json file.

**Comment by adamwathan** [comment]
@SimonPrague Just spent 20 minutes recreating your project manually, the issue in your config is `presets: []` in your `tailwind.config.js` file. You are telling Tailwind to disable the default config which causes things to blow up when you don't provide everything it's expecting manually. We can make this fail more gracefully for sure but this gets your project to build fine:

```diff
  // tailwind.config.js
  module.exports = {
    // ...
-   presets: []
    // ...
  }
```

**Comment by JustCarty** [comment]
I had this issue until I updated Node.js from `v10.16.0` to `v14.15.1`.

My `package.json` is:
```json
"dependencies": {
    "autoprefixer": "^10.0.2",
    "postcss": "^8.1.9",
    "tailwindcss": "^2.0.1"
}
```

Hopefully this helps anyone who needs the latest version, and doesn't want to use the compatibility version.  
That being said, even the compatibility version didn't work for me - so I guess just make sure Node.js is up to date (note: not NPM, although make sure that's up to date too)!

**Comment by SimonPrague** [comment]
> @SimonPrague Just spent 20 minutes recreating your project manually, the issue in your config is `presets: []` in your `tailwind.config.js` file. You are telling Tailwind to disable the default config which causes things to blow up when you don't provide everything it's expecting manually. We can make this fail more gracefully for sure but this gets your project to build fine:
> 
> ```diff
>   // tailwind.config.js
>   module.exports = {
>     // ...
> -   presets: []
>     // ...
>   }
> ```

Adam, thanks so much! I really appreciate your 20 minutes spending on it. I spent over 5 hours on it and could not figure it out. Anyway thanks a ton. Also love the Tailwind & Tailwind UI!

**Comment by jdhaines** [comment]
> @SimonPrague Just spent 20 minutes recreating your project manually, the issue in your config is `presets: []` in your `tailwind.config.js` file. You are telling Tailwind to disable the default config which causes things to blow up when you don't provide everything it's expecting manually. We can make this fail more gracefully for sure but this gets your project to build fine:
> 
> ```diff
>   // tailwind.config.js
>   module.exports = {
>     // ...
> -   presets: []
>     // ...
>   }
> ```

Thanks for this... I was also tearing my hair out with this one.  I generated a default config when upgrading to Tailwind2 and this line was in there.  Commenting it out fixed everything.  Is there a chance this should be commented out by default when creating a new config?  I don't really know, but wanted to ask the question at least.  Thanks again for the help.

**Comment by needcaffeine** [comment]
This error went away for me when I switched from node 10 to 12. Hopefully that helps someone.

**Comment by evijayan2** [comment]
> It appears the issue is that the tailwindcss package installed under my node_modules (`./node_modules/tailwindcss/node_modules`) has the `postcss` package installed under it at version 7.0.32. I am assuming this serves as an override to my "root" postcss package which is installed at version 8.1.8. Removing `node_modules/tailwindcss/node_modules/postcss` solves the problem and my project now builds.
> 
> Perhaps someone here understands why tailwindcss is including that older postcss dep into itself and how to permanently fix this? It looks to me like tailwindcss has `"@fullhuman/postcss-purgecss": "^3.0.0"` as a dependency and that in turn has a postcss v7 dependency which in turn overrides my global v8.

after remove the `node_modules/tailwindcss/node_modules/postcss` ran `ng serve` it worked

**Comment by seankndy** [comment]
> > It appears the issue is that the tailwindcss package installed under my node_modules (`./node_modules/tailwindcss/node_modules`) has the `postcss` package installed under it at version 7.0.32. I am assuming this serves as an override to my "root" postcss package which is installed at version 8.1.8. Removing `node_modules/tailwindcss/node_modules/postcss` solves the problem and my project now builds.
> > Perhaps someone here understands why tailwindcss is including that older postcss dep into itself and how to permanently fix this? It looks to me like tailwindcss has `"@fullhuman/postcss-purgecss": "^3.0.0"` as a dependency and that in turn has a postcss v7 dependency which in turn overrides my global v8.
> 
> after remove the `node_modules/tailwindcss/node_modules/postcss` ran `ng serve` it worked

Go ahead and run "npm install" to put that directory back.  Then install the compat packages as suggested by @ThreeScreenStudios which solved my issue.

```
npm remove tailwindcss
npm remove postcss
npm install tailwindcss@npm:@tailwindcss/postcss7-compat
```

**Comment by jstoppa** [comment]
upgrading node to 14.15.1 as @CreateSean suggested solved my issue

**Comment by mattrunyon** [comment]
I'm getting the same `getProcessedPlugins is not a function` error.

postcss 8.1.0
postcss-import 13.0.0
postcss-loader 4.1.0
webpack 5.9.0
tailwindcss 2.0.1
node 14.15.1

postcss config
```
module.exports = {
  plugins: [
    require('postcss-import'),
    require('tailwindcss'),
    require('autoprefixer'),
  ],
};
```

tailwind config
```
module.exports = {
  purge: ['./src/client/**/*.jsx'],
  theme: {
    extend: {
      colors: {
        primary: '#f9a825',
        secondary: '#eeeeee',
      },
    },
  },
};
```

When I remove tailwind from the postcss plugins, everything compiles fine (CSS is broken of course)

Downgrading to the compat version of tailwind works; however, why should I need to use compat? The docs say if the plugins being used work with postcss 8 then the compat version is unnecessary. The other plugins I'm using work just fine with postcss 8 when tailwind is removed. It's only when tailwind is added that it breaks.

**Comment by naknode** [comment]
> upgrading node to 14.15.1 as @CreateSean suggested solved my issue

This worked for me as well. I was on Node v10. I upgraded to Node v14 as suggested and all is well.

**Comment by brahmendernchary** [comment]
i solve this issue update to my node version 14

**Comment by jiangyh1024** [comment]
anybody can help ? I stll got the error even though I followed the steps on document

![image](https://user-images.githubusercontent.com/34930870/102048816-bf085c00-3e1a-11eb-8f9d-1fff75716d24.png)
![image](https://user-images.githubusercontent.com/34930870/102048820-c0d21f80-3e1a-11eb-8d8f-269022da7fac.png)
![image](https://user-images.githubusercontent.com/34930870/102048834-c6c80080-3e1a-11eb-8293-4aa5040d9cf1.png)

**Comment by jiangyh1024** [comment]
solved by upgrading node to LST version

**Comment by Pblfer** [comment]
> Check your nodejs version (node -v) , I had v10.19.0, then made global update to v14.15.1, using vue-cli with the following dependencies
> `"dependencies": { "autoprefixer": "^9.8.6", "core-js": "^3.6.5", "postcss": "^7.0.35", "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.1", "vue": "^2.6.11", "vue-router": "^3.4.9" },`
> 
> After updating node and running npm run serve I was able to build the tailwind under vue-cli
> 
> postcss.config.js
> `module.exports = { plugins: [ require('tailwindcss'), require('autoprefixer'), ] }`
> 
> tailwind.config.js
> `module.exports = { purge: { content: ['./public/**/*.html', './src/**/*.vue'] }, darkMode: false, // or 'media' or 'class' theme: { extend: {}, }, variants: { extend: {}, }, plugins: [], } `

These work for me! 👌

**Comment by hachi-studio** [comment]
Also solved via node version!

**Comment by carbontwelve** [comment]
I know this issue is closed, however I had the same `TypeError: getProcessedPlugins is not a function` error crop up in my github actions but not on my local. Using `npm ci` followed by my build command would work on my local box but not within my github action.

I found the cause to be my local is running node v12.18.1 (npm v6.14.5) and the failing Github action was using node v10.23.0 (npm v6.14.8) updating my Github Actions config to use the same version of node as my local stopped the build from failing.

I am unsure if this is documented anywhere @adamwathan but I have seen it suggested by a few other members of the community and can confirm it was the cause of this issue in my case.

**Comment by Youhan** [comment]
Could be Node version too. If you use nvm like me, check if your Node is => 12

**Comment by Rolando-Barbella** [comment]
It works for me with node 11

**Comment by liaoliaojun** [comment]
> Vue 3

me  https://github.com/liaoliaojun/nuxt-apollo-example

**Comment by jlooper** [comment]
In case someone bumps into this when deploying to Netlify (just when you thought everything was perfect locally...) you can add a .node-version file to your site root and just specify 14 as the version. That makes it build and deploy ok on Netlify.

**Comment by mittalvaibhav** [comment]
> Check your nodejs version (node -v) , I had v10.19.0, then made global update to v14.15.1, using vue-cli with the following dependencies
> `"dependencies": { "autoprefixer": "^9.8.6", "core-js": "^3.6.5", "postcss": "^7.0.35", "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.1", "vue": "^2.6.11", "vue-router": "^3.4.9" },`
> 
> After updating node and running npm run serve I was able to build the tailwind under vue-cli
> 
> postcss.config.js
> `module.exports = { plugins: [ require('tailwindcss'), require('autoprefixer'), ] }`
> 
> tailwind.config.js
> `module.exports = { purge: { content: ['./public/**/*.html', './src/**/*.vue'] }, darkMode: false, // or 'media' or 'class' theme: { extend: {}, }, variants: { extend: {}, }, plugins: [], } `

After updating the nodejs version to v14.15.4, my issue is gone

**Comment by shuzootani** [comment]
in my case, updating node version to v14.7.0 from v10.22.0 fixed the error in Next.js app.
thanks to https://github.com/tailwindlabs/tailwindcss/issues/2810#issuecomment-730657685

**Comment by rifandani** [comment]
> @SimonPrague Just spent 20 minutes recreating your project manually, the issue in your config is `presets: []` in your `tailwind.config.js` file. You are telling Tailwind to disable the default config which causes things to blow up when you don't provide everything it's expecting manually. We can make this fail more gracefully for sure but this gets your project to build fine:
> 
> ```diff
>   // tailwind.config.js
>   module.exports = {
>     // ...
> -   presets: []
>     // ...
>   }
> ```

This solutions works on my Next.js project! Thanks

**Comment by cooskun** [comment]
Updating the node to the latest version(v15.7.0) solved the problem for me!

**Comment by Mancancode** [comment]
Hi i fixed the error "TypeError: getProcessedPlugins is not a function" by updating my Nodejs to newer version of 12.22.1
i hope this helps.

**Comment by MiguelAngelParedesBustos** [comment]
you need to update nvm. do `nvm install {latest version}`, then `npm run dev` and it works

**Comment by darekkay** [comment]
I've had the same issue, but it had nothing to do with the Node version. The issue was that I've [disabled the default configuration](https://tailwindcss.com/docs/presets#disabling-the-default-configuration) without providing default values for enabled plugins:

```
module.exports = {
  presets: [],
  theme: {
    // if this line is missing, I'm getting an error
    // backgroundColor: { ... } 
  },
  corePlugins: {
    backgroundColor: true
  }
}
```

The error message actually points to this issue, as there are two errors:

> Stack:
> TypeError: **Cannot convert undefined or null to object**
>     at Function.entries (<anonymous>)
>     at flattenColorPalette (node_modules\tailwindcss\lib\util\flattenColorPalette.js:8:67)
>     at node_modules\tailwindcss\lib\plugins\\**backgroundColor.js**:27:53
> 
> Stack:
> TypeError: **getProcessedPlugins is not a function**
>     at node_modules\tailwindcss\lib\processTailwindFeatures.js:75:83

So the error is indeed correct, but I guess the error message could be improved.

**Comment by patoncrispy** [comment]
A problem I had was that I had properties under `variants` that should have been under `variants.extend`. Also, some properties were no longer valid there and had to be moved to `theme.extend`. Hope that helps someone else.

**Comment by mpakaris** [comment]
> > @SimonPrague Just spent 20 minutes recreating your project manually, the issue in your config is `presets: []` in your `tailwind.config.js` file. You are telling Tailwind to disable the default config which causes things to blow up when you don't provide everything it's expecting manually. We can make this fail more gracefully for sure but this gets your project to build fine:
> > ```diff
> >   // tailwind.config.js
> >   module.exports = {
> >     // ...
> > -   presets: []
> >     // ...
> >   }
> > ```
> 
> This solutions works on my Next.js project! Thanks

This worked for me as well!

**Comment by danielbachhuber** [comment]
> > > @SimonPrague Just spent 20 minutes recreating your project manually, the issue in your config is `presets: []` in your `tailwind.config.js` file. You are telling Tailwind to disable the default config which causes things to blow up when you don't provide everything it's expecting manually. We can make this fail more gracefully for sure but this gets your project to build fine:
> > > ```diff
> > >   // tailwind.config.js
> > >   module.exports = {
> > >     // ...
> > > -   presets: []
> > >     // ...
> > >   }
> > > ```
> > 
> > 
> > This solutions works on my Next.js project! Thanks
> 
> This worked for me as well!

Me too! I'm glad it was an easy fix for such a cryptic error 😄

**Comment by lohnsonok** [comment]
> @alexcroox I managed to fix it on my end.
> 
> What I did was I removed the existing `tailwind.config.js` and just ran the command `npx tailwindcss init --full`, then I just applied the custom configurations that I did to it. I'm going to close the issue since I fixed my original issue

it worked for me too ! Thank you

**Comment by 88brmig** [comment]
> @alexcroox I managed to fix it on my end.
> 
> What I did was I removed the existing `tailwind.config.js` and just ran the command `npx tailwindcss init --full`, then I just applied the custom configurations that I did to it. I'm going to close the issue since I fixed my original issue

damn king, you rock! It work for me either.

**Comment by coolcorexix** [comment]
> @SimonPrague Just spent 20 minutes recreating your project manually, the issue in your config is `presets: []` in your `tailwind.config.js` file. You are telling Tailwind to disable the default config which causes things to blow up when you don't provide everything it's expecting manually. We can make this fail more gracefully for sure but this gets your project to build fine:
> 
> ```diff
>   // tailwind.config.js
>   module.exports = {
>     // ...
> -   presets: []
>     // ...
>   }
> ```

Actually that 
```
> -   presets: []
```
Is included when run command `npx tailwindcss init --full`. And this is from the team, I supposed?
Btw the fix worked for me, thank you very much

**Comment by emmaroland32** [comment]
> > @SimonPrague Just spent 20 minutes recreating your project manually, the issue in your config is `presets: []` in your `tailwind.config.js` file. You are telling Tailwind to disable the default config which causes things to blow up when you don't provide everything it's expecting manually. We can make this fail more gracefully for sure but this gets your project to build fine:
> > ```diff
> >   // tailwind.config.js
> >   module.exports = {
> >     // ...
> > -   presets: []
> >     // ...
> >   }
> > ```
> 
> This solutions works on my Next.js project! Thanks



> @SimonPrague Just spent 20 minutes recreating your project manually, the issue in your config is `presets: []` in your `tailwind.config.js` file. You are telling Tailwind to disable the default config which causes things to blow up when you don't provide everything it's expecting manually. We can make this fail more gracefully for sure but this gets your project to build fine:
> 
> ```diff
>   // tailwind.config.js
>   module.exports = {
>     // ...
> -   presets: []
>     // ...
>   }
> ```

Thanks! This worked for me with Next.js.

**Comment by jakecausier** [comment]
Similar to what @patoncrispy said, I had my config with the following value for variants:
```
variants: {
  transitionProperty: {
    'spacing': 'margin, padding'
  }
}
```
This was causing the root of my issues for not using `extend: {}` inside it, and using object notation instead of array for the properties.

**Comment by sjwinther** [comment]
Getting this error when referring to theme in my config, like so: `brand: (theme) => theme('colors.orange')`. Works when the line is commented out. Fully updated Next.js, PostCSS and Tailwind, Node v15.9.0. Full config here: https://github.com/tailwindlabs/tailwindcss/discussions/5708.

Doesn't look like it's the preset or variants error as described above. All help appreciated
