### ISSUE TITLE
[Bug]: Problem comparing configs (Unknown object type)

### ISSUE THREAD

**Issue by lfrancke** [tailwindlabs/tailwindcss#4212]
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

gulp 2.3.0, npm 7.11.2, postcss 8.2.13

### What version of Node.js are you using?

14.16.0

### What browser are you using?

n/a

### What operating system are you using?

Linux

### Reproduction repository

https://github.com/stackabletech/documentation-ui (tailwind branch)

### Describe your issue

Running `npm install` followed by `gulp bundle` in the repository (tailwind branch) leads to this error

```
Message:
    Unknown object type "promise"
Details:
    fileName: /home/lars/dev/stackable/documentation-ui/src/css/site.css
    domainEmitter: [object Object]
    domainThrown: false

Stack:
Error: Unknown object type "promise"
    at Object._object (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:223:17)
    at Object.dispatch (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:190:30)
    at /home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:251:18
    at Array.forEach (<anonymous>)
    at Object._object (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:247:21)
    at Object._function (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:324:14)
    at Object.dispatch (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:190:30)
    at /home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:251:18
    at Array.forEach (<anonymous>)
    at Object._object (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:247:21)
```
When I remove [this line](https://github.com/stackabletech/documentation-ui/blob/56235d138765e04d8ac6471f7b2b086bdb8296a2/gulp.d/tasks/build.js#L53) everything works.

I narrowed this down to this line:
https://github.com/tailwindlabs/tailwindcss/blob/3843700470db000e0dcd3aada0f700bf75bdca1e/src/processTailwindFeatures.js#L30

When I change it to `const configChanged = true` everything works as expected.
This means there must be _something_ in the config that the `object-hash` library can't process.

Unfortunately, I have very little JavaScript knowledge but it seems like one sensible way would be to catch errors here and set `configChanged` to `true` but I have to admit I don't know the full repercussions of this.

On Node 16 the type is different it complains about: `asyncgeneratorfunction`

I have to admit that the example is probably not _minimal_ but I lack the knowledge to minimize it any more. So feel free to close if this is not helpful.

**Comment by billrobclark** [comment]
Yo

**Comment by adamwathan** [comment]
Hey! This looks like [an upstream bug](https://github.com/puleos/object-hash/issues/95) but I've pushed a change that should at least bypass the error. You may have to rebuild your CSS manually if you make changes to the part of your config that comes from a promise though.

Should be able to install the latest canary to test this out until it makes its way into a proper release:

`npm install -D tailwindcss@canary`

**Comment by lfrancke** [comment]
Thank you for the quick fix. I'll try it out!

**Comment by lfrancke** [comment]
This seems to kick the can down the road to the next issue

```
TypeError: Symbol.prototype.toString requires that 'this' be a Symbol
    at Symbol.toString (<anonymous>)
    at Object._symbol (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:300:36)
    at Object._object (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:219:30)
    at Object.dispatch (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:190:30)
    at /home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:252:18
    at Array.forEach (<anonymous>)
    at Object._object (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:247:21)
    at Object._function (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:328:14)
    at Object.dispatch (/home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:190:30)
    at /home/lars/dev/stackable/documentation-ui/node_modules/object-hash/index.js:252:18
```

Happy to create a new issue or reopen this? This time I have even less of an idea what's going on.

**Comment by marshalladam** [comment]
This is still happening with tailwind 2.14.0 - couldn't install tailwindcss@canary because I get the following error: 
```npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: tailwindcss@2.2.0-canary.14
npm ERR! node_modules/tailwindcss
npm ERR!   tailwindcss@"2.2.0-canary.14" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@">=2.0.0" from @tailwindcss/forms@0.3.3
npm ERR! node_modules/@tailwindcss/forms
npm ERR!   @tailwindcss/forms@"^0.3.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.```
